### ISSUE TITLE
Create a high-resolution (SVG) version of pixel art logo

### ISSUE THREAD

**Issue by igalic** [voxpupuli/logos#4]
Our [pixel-art logo](https://github.com/voxpupuli/logos/blob/master/images/8bit-vox.png), while PNG, and as such a very high-quality form, should be supplemented with an SVG form for INFINITE SCALING (Web 2.0?)

**Comment by wavebeem** [comment]
Writing a script to turn the pixels into a bunch of SVG `<rect>` tags should work: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect

**Comment by bastelfreak** [comment]
![scaling](https://cloud.githubusercontent.com/assets/341866/20689462/d32bcc6c-b5c5-11e6-8c8c-3c37bfc4538a.jpg)

**Comment by wavebeem** [comment]
It's already been made! http://florian-berger.de/en/software/pixel2svg/

![bitmoji](https://render.bitstrips.com/v2/cpanel/10211507-178219398_4-s4-v1.png?transparent=1&width=246)
